### ISSUE TITLE
Can we get a crate version targeting digest 0.8 please?

### ISSUE THREAD

**Issue by gilescope** [RustCrypto/MACs#10]
Can we get a version targeting digest 0.8 please as sha2 has moved on?

Many thanks!

**Comment by newpavlov** [comment]
You mean `hmac` crate, right? `hmac v0.7` is already [defined](https://crates.io/crates/hmac) in terms of `digest v0.8` traits. Versions of `crypto-mac` and crates in this repository are not synchronized with `digest` version
