### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by Mach1212** [RustCrypto/MACs#113]
![image](https://user-images.githubusercontent.com/45501415/159061509-1406d0fb-377f-423e-b9c6-ad0032ba806d.png)
The default example doesn't seem to work for me and running cargo check in the terminal confirms it.

[dependencies]
sha2 = "0.10.2"
hmac = "0.12.1"

**Comment by newpavlov** [comment]
As the help message notes, you haven't imported the necessary trait. Take a careful look at [the `hmac` crate docs](https://docs.rs/hmac).

**Comment by Mach1212** [comment]
Thank you! I didn't realize I had to import the trait.
