### ISSUE TITLE
implementation of Reset is now behind feature flag. 

### ISSUE THREAD

**Issue by Charles-Schleich** [RustCrypto/MACs#119]
Looks like updating from `11.0` -> `12.1` moved the Implementation of Reset behind a feature flag.

`hmac = {version="0.12.1", features=["reset"]}` 
in your Cargo.toml will fix issues like   

```
56 |         let sign = mac.finalize_reset().into_bytes();
   |                        ^^^^^^^^^^^^^^ the trait `Reset` is not implemented for `HmacCore<CoreWrapper<CtVariableCoreWrapper<Sha256VarCore, sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<sha2::digest::typenum::UInt<UTerm, B1>, B0>, B0>, B0>, B0>, B0>, OidSha256>>>`
```
For types like `hmac::Hmac<sha2::Sha256>`, `hmac::Hmac<sha2::Sha384>`, `hmac::Hmac<sha2::Sha512>`

Putting this here purely so I help someone else arrive at the same conclusion faster.

**Comment by benma** [comment]
Thanks! Maintainers, please add a changelog file.

**Comment by newpavlov** [comment]
@benma 
Done in #121
