### ISSUE TITLE
cmac: size of cavp_aes128.blb

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/MACs#127]
I noticed this file is bringing the total size of the crate to >1MB. Previous releases were 9kB before that.

Is there any reason why it's so large?

**Comment by newpavlov** [comment]
It contains 16 vectors with 65536 bytes of input data. We either can remove those values or move CAVP AES-128 into a separate module which will be excluded from package together with `cavp_aes128.blb`.

**Comment by tarcieri** [comment]
Excluding it from the crate sounds good, if it can be done without breaking the tests (possibly using `#[ignore]`?)
