### ISSUE TITLE
Turn DynDigest into Hmac/Mac

### ISSUE THREAD

**Issue by jeapostrophe** [RustCrypto/MACs#173]
The `digest` package defines a `DynDigest` trait for dynamically referenced digests. I would like to take one of these and turn it into an `Hmac` instance. I think that `new_from_slice` could have a variant where the `digest` is passed in as an argument, rather than being generated internally. I suppose the danger with this is that the digest might not be the default, but `Digest` already has a `reset` function, which could be used in cases where the digest was passed this way. Is there something I'm not thinking of that would prevent implementing this?

**Comment by newpavlov** [comment]
HMAC needs to know block size, which is not exposed by `DynDigest`. Also note that `new_from_slice` is part of the `KeyInit` trait.

I think a better option will be to define a `DynMac` trait in your project and cast initialized `Hmac<Sha256>` to `&mut dyn DynMac`. Supporting `Hmac<Box<dyn DynDigest>>` will involve a fair bit of headaches, so I don't think it's worth the trouble.

**Comment by jeapostrophe** [comment]
Thank you for the advice!

**Comment by eqvinox** [comment]
I found this issue trying to do the same thing more or less; could some notes on this be added to the documentation? — or even a `DynMac` be part of the crate?
