### ISSUE TITLE
Support non-cloneable BlockCiphers

### ISSUE THREAD

**Issue by Dirbaio** [RustCrypto/MACs#47]
Currently the MACs that use block ciphers (`CMAC`, `PMAC`) require the `BlockCipher` in use to be `Clone`.

It seems to me that it should be possible to not require `Clone`. Instead, conditionally implement `Clone` for the `Mac` if the `BlockCipher` is `Clone`?

This would be a breaking change though. Generic code that needs cloning is now requiring just `Mac`, and it'll now have to require `Mac + Clone`

My use case is using a custom block cipher that contains `&mut`'s inside, so it can't be cloned. (I know it's weird, it's a cipher that does very expensive calculations that sometimes can be cached so it has a mutable ref to a cache).

**Comment by tarcieri** [comment]
It might be possible to support a blanket impl of `BlockCipher` for reference types of `BlockCipher`, which in theory could eliminate the `Clone` bound by leveraging immutable borrows. See @newpavlov's suggestion here:

https://github.com/RustCrypto/block-ciphers/issues/132#issuecomment-642782031

>  I wonder if we can add `impl<T: BlockCipher> BlockCipher for &T`, this could make it possible to instantiate a block mode using block cipher reference (although we would have to slightly change `BlockCipher` definition to accommodate for that).

**Comment by Dirbaio** [comment]
That makes sense! I was looking for the possibility of using a `&mut` but a `&` would work too, I guess I can use interior mutability.

**Comment by tarcieri** [comment]
We did also (very) recently add [BlockCipherMut](https://docs.rs/block-cipher/latest/block_cipher/trait.BlockCipherMut.html) but aren't using it for anything yet.
