### ISSUE TITLE
sha2 0.8 incompatability

### ISSUE THREAD

**Issue by theduke** [RustCrypto/MACs#7]
Seems like sha2 0.8 had some breaking changes, making it incompatible with hmac 0.6.

I was very confused for a while until I checked the sha2 version in the tests and noticed the 0.7 <-> 0.8 difference.

An update would be great, but also posting this as an FYI if someone else stumbles over the issue.

**Comment by newpavlov** [comment]
Yes, sorry for the confusion. The update is currently being [worked on](https://github.com/RustCrypto/MACs/pull/6). I will publish it in the following 10-20 hours. (I want to do it synchronously with other MAC crates)
