### ISSUE TITLE
hmac: Missing CHANGELOG entry for NewMac::new_from_slice

### ISSUE THREAD

**Issue by str4d** [RustCrypto/MACs#77]
It looks like `hmac::NewMac::new_varkey` was renamed to `hmac::NewMac::new_from_slice` in 0.11.

**Comment by tarcieri** [comment]
I suppose we could add a summary of what changed upstream in the `crypto-mac` crate to each of the MAC crtes

**Comment by str4d** [comment]
Oh, then move this issue there, because it's not documented there either.

**Comment by str4d** [comment]
Aha, I see: it was changed for both `cipher` and `crypto-mac` (https://github.com/RustCrypto/traits/pull/442), but only documented in the changelog for `cipher`.

**Comment by str4d** [comment]
Opened https://github.com/RustCrypto/traits/issues/626.
