### ISSUE TITLE
Hashing file functions

### ISSUE THREAD

**Issue by nifker** [RustCrypto/MACs#8]
If there is interest I can add functions for reading whole/parts of files into the mac hasher.

**Comment by newpavlov** [comment]
Hm, I think we should instead implement `io::Write` for all implementations behind `std` feature flag in the same fashion as for [hashes](https://github.com/RustCrypto/hashes/blob/master/md5/src/lib.rs#L123).

**Comment by nifker** [comment]
I guess that the macro used for hashes does not work for the Mac types here or?
