### ISSUE TITLE
hmac 0.7.0 has a yanked dependency on crypto-mac

### ISSUE THREAD

**Issue by blakehawkins** [RustCrypto/MACs#92]
I'm using coinbase-rs which has a dependency on hmac, causing builds to fail like this:

```
$ cargo run
    Updating crates.io index
error: failed to select a version for the requirement `crypto-mac = "^0.7"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `hmac v0.7.0`
    ... which is depended on by `coinbase-rs v0.3.0`
    ... which is depended on by `cb-candles v0.1.0 (/home/blake/workspace/cb-candles)`
```

hmac already has a bumped version of crypto-mac, but should yank 0.7.0 so that coinbase-rs builds fail

**Comment by tarcieri** [comment]
I've put it back for now.

Please open an issue to have `coinbase-rs` update `hmac`.

`hmac` v0.7.0 is nearly 3 years old.

**Comment by blakehawkins** [comment]
Yep have done so https://github.com/j16r/coinbase-rs/issues/7

But you should yank hmac 0.7 as this will quietly compile successfully atm in coinbase-rs
